Repository blackMisay/Janmos, pull requests merged in 2024-03, with the labels that each got.

#8 feature/JSAI3 - Design of Product Interface
  App/App.csproj
  App/Main.Designer.cs
  App/Product/Product.Designer.cs
  App/Product/Product.cs
  App/Product/ProductModal.Designer.cs
  App/Product/ProductModal.cs
  App/Product/ProductModal.resx
Labels: enhancement

#11 feature/JSAI3 - Change Background Color Product Interface
  App/App.csproj
  App/Main.cs
  App/Product/Product.Designer.cs
  App/Product/ProductModal.Designer.cs
Labels: enhancement, review

#12 feature/JSAI4 - Design Customer Interface
  App/Customer/Customer.Designer.cs
  App/Customer/Customer.cs
  App/Customer/CustomerModal.Designer.cs
  App/Customer/CustomerModal.cs
  App/Customer/CustomerModal.resx
Labels: enhancement, review

#9 feature/JSAI5 - Implement User Login Authentication
  App/App.csproj
  App/Login.Designer.cs
  App/Login.cs
  App/Login.resx
  Core/Core.csproj
  Core/System/Data/Model/User.cs
  Core/System/Data/UpgradeManager.cs
  Core/System/Security/SecureHash.cs
  Core/System/Security/UserAuthentication.cs
Labels: enhancement

#22 [Branch Maintenance] feature/JSAI12
  App/App.csproj
  App/Customer/Customer.Designer.cs
  App/Customer/Customer.cs
  App/Customer/CustomerModal.Designer.cs
  App/Customer/CustomerModal.cs
  App/Customer/CustomerModal.resx
  App/Dashboard/Dashboard.Designer.cs
  App/Dashboard/Dashboard.cs
  App/Dashboard/Dashboard.resx
  App/Login.Designer.cs
  App/Login.cs
  App/Login.resx
  App/Main.Designer.cs
  App/Main.cs
  App/Product/Product.Designer.cs
  App/Product/Product.cs
  App/Product/ProductModal.Designer.cs
  App/Product/ProductModal.cs
  App/Product/ProductModal.resx
  Core/Core.csproj
  Core/System/Data/Model/User.cs
  Core/System/Data/UpgradeManager.cs
  Core/System/Security/SecureHash.cs
  Core/System/Security/UserAuthentication.cs
Labels: branch maintenance

#23 feature/JSAI2 - Implement new interface for Main form
  App/App.csproj
  App/Customer/Customer.Designer.cs
  App/Main.Designer.cs
  App/Main.cs
  App/Main.resx
  App/Properties/Resources.Designer.cs
  App/Properties/Resources.resx
  App/Resources/account_24px.png
  App/Resources/customer_24px.png
  App/Resources/dashboard_24px.png
  App/Resources/inventory_24px.png
  App/Resources/menu-bar_24px.png
  App/Resources/product_24p.png
  App/Resources/product_24px.png
  App/Resources/reports_24px.png
  App/Resources/settings_24px.png
  App/Resources/supplier_24px.png
Labels: review

#24 enhance/JSAI17 - Implement Product functionalities
  App/App.csproj
  App/Customer/frmCustomer.Designer.cs
  App/Customer/frmCustomer.cs
  App/Customer/frmCustomer.resx
  App/Customer/frmCustomerModal.Designer.cs
  App/Customer/frmCustomerModal.cs
  App/Customer/frmCustomerModal.resx
  App/Main.cs
  App/Product/Product.cs
  App/Product/ProductModal.cs
  App/Product/frmProduct.Designer.cs
  App/Product/frmProduct.cs
  App/Product/frmProduct.resx
  App/Product/frmProductModal.Designer.cs
  App/Product/frmProductModal.cs
  App/Product/frmProductModal.resx
  Core/Core.csproj
  Core/System/Data/Model/Category.cs
  Core/System/Data/Model/MetricUnit.cs
  Core/System/Data/Model/Product.cs
  Core/System/Repository/ProductRepository.cs
Labels: review

#26 [Branch Maintenance] enhance/JSAI17
  App/App.csproj
  App/Customer/frmCustomer.Designer.cs
  App/Customer/frmCustomer.cs
  App/Customer/frmCustomer.resx
  App/Customer/frmCustomerModal.Designer.cs
  App/Customer/frmCustomerModal.cs
  App/Customer/frmCustomerModal.resx
  App/Main.Designer.cs
  App/Main.cs
  App/Main.resx
  App/Properties/Resources.Designer.cs
  App/Properties/Resources.resx
  App/Resources/account_24px.png
  App/Resources/customer_24px.png
  App/Resources/dashboard_24px.png
  App/Resources/firstpage_16px.png
  App/Resources/inventory_24px.png
  App/Resources/lastpage_16px.png
  App/Resources/menu-bar_24px.png
  App/Resources/nextpage_16px.png
  App/Resources/previouspage_16px.png
  App/Resources/product_24p.png
  App/Resources/product_24px.png
  App/Resources/reports_24px.png
  App/Resources/settings_24px.png
  App/Resources/supplier_24px.png
Labels: review, branch maintenance

#28 enhance/JSAI15 - Implement enhancement in Product Module UI
  App/Customer/frmCustomer.Designer.cs
  App/Customer/frmCustomer.resx
  App/Main.Designer.cs
  App/Product/frmProduct.Designer.cs
  App/Product/frmProduct.cs
  App/Product/frmProduct.resx
  App/Product/frmProductModal.Designer.cs
  App/Product/frmProductModal.cs
  App/Product/frmProductModal.resx
  Core/System/Repository/ProductRepository.cs
Labels: enhancement, review

#53 bug/JSAI30 - Implement new interface for Login
  App/App.csproj
  App/Login.Designer.cs
  App/Login.resx
  App/Properties/Resources.Designer.cs
  App/Properties/Resources.resx
  App/Resources/inventory-management.png
  App/Resources/inventory-management_logo.png
Labels: bug
